language: python

python:
  - 3.7
  - 3.6

script:
  - pip install --upgrade pip
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt

  - flake8 .
  - black --check .
  - pytest
  - coverage xml -o coverage.xml

after_success:
  - codecov -t ef816643-aeda-4fa9-ad22-37709386f4cf
